package org.lwjgl.opengl;

// Generated by tools-src/GenerateHdGlesBase.java from the Android SDK.
public class GlesBindings {
    public static boolean glUnmapBuffer(int a0) { return android.opengl.GLES32.glUnmapBuffer(a0); }
    public static int glCreateProgram() { return android.opengl.GLES32.glCreateProgram(); }
    public static int glCreateShader(int a0) { return android.opengl.GLES32.glCreateShader(a0); }
    public static int glGetError() { return android.opengl.GLES32.glGetError(); }
    public static int glGetUniformLocation(int a0,java.lang.String a1) { return android.opengl.GLES32.glGetUniformLocation(a0,a1); }
    public static int glClientWaitSync(long a0,int a1,long a2) { return android.opengl.GLES32.glClientWaitSync(a0,a1,a2); }
    public static int glGetUniformBlockIndex(int a0,java.lang.String a1) { return android.opengl.GLES32.glGetUniformBlockIndex(a0,a1); }
    public static java.lang.String glGetProgramInfoLog(int a0) { return android.opengl.GLES32.glGetProgramInfoLog(a0); }
    public static java.lang.String glGetShaderInfoLog(int a0) { return android.opengl.GLES32.glGetShaderInfoLog(a0); }
    public static java.lang.String glGetString(int a0) { return android.opengl.GLES32.glGetString(a0); }
    public static java.nio.Buffer glMapBufferRange(int a0,int a1,int a2,int a3) { return android.opengl.GLES32.glMapBufferRange(a0,a1,a2,a3); }
    public static long glFenceSync(int a0,int a1) { return android.opengl.GLES32.glFenceSync(a0,a1); }
    public static void glActiveTexture(int a0) { android.opengl.GLES32.glActiveTexture(a0); }
    public static void glAttachShader(int a0,int a1) { android.opengl.GLES32.glAttachShader(a0,a1); }
    public static void glBindBuffer(int a0,int a1) { android.opengl.GLES32.glBindBuffer(a0,a1); }
    public static void glBindFramebuffer(int a0,int a1) { android.opengl.GLES32.glBindFramebuffer(a0,a1); }
    public static void glBindRenderbuffer(int a0,int a1) { android.opengl.GLES32.glBindRenderbuffer(a0,a1); }
    public static void glBindTexture(int a0,int a1) { android.opengl.GLES32.glBindTexture(a0,a1); }
    public static void glBlendFuncSeparate(int a0,int a1,int a2,int a3) { android.opengl.GLES32.glBlendFuncSeparate(a0,a1,a2,a3); }
    public static void glBufferData(int a0,int a1,java.nio.Buffer a2,int a3) { android.opengl.GLES32.glBufferData(a0,a1,a2,a3); }
    public static void glBufferSubData(int a0,int a1,int a2,java.nio.Buffer a3) { android.opengl.GLES32.glBufferSubData(a0,a1,a2,a3); }
    public static void glClear(int a0) { android.opengl.GLES32.glClear(a0); }
    public static void glClearColor(float a0,float a1,float a2,float a3) { android.opengl.GLES32.glClearColor(a0,a1,a2,a3); }
    public static void glColorMask(boolean a0,boolean a1,boolean a2,boolean a3) { android.opengl.GLES32.glColorMask(a0,a1,a2,a3); }
    public static void glCompileShader(int a0) { android.opengl.GLES32.glCompileShader(a0); }
    public static void glDeleteBuffers(int a0,int[] a1,int a2) { android.opengl.GLES32.glDeleteBuffers(a0,a1,a2); }
    public static void glDeleteBuffers(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glDeleteBuffers(a0,a1); }
    public static void glDeleteFramebuffers(int a0,int[] a1,int a2) { android.opengl.GLES32.glDeleteFramebuffers(a0,a1,a2); }
    public static void glDeleteFramebuffers(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glDeleteFramebuffers(a0,a1); }
    public static void glDeleteProgram(int a0) { android.opengl.GLES32.glDeleteProgram(a0); }
    public static void glDeleteRenderbuffers(int a0,int[] a1,int a2) { android.opengl.GLES32.glDeleteRenderbuffers(a0,a1,a2); }
    public static void glDeleteRenderbuffers(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glDeleteRenderbuffers(a0,a1); }
    public static void glDeleteShader(int a0) { android.opengl.GLES32.glDeleteShader(a0); }
    public static void glDeleteTextures(int a0,int[] a1,int a2) { android.opengl.GLES32.glDeleteTextures(a0,a1,a2); }
    public static void glDeleteTextures(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glDeleteTextures(a0,a1); }
    public static void glDepthFunc(int a0) { android.opengl.GLES32.glDepthFunc(a0); }
    public static void glDepthMask(boolean a0) { android.opengl.GLES32.glDepthMask(a0); }
    public static void glDetachShader(int a0,int a1) { android.opengl.GLES32.glDetachShader(a0,a1); }
    public static void glDisable(int a0) { android.opengl.GLES32.glDisable(a0); }
    public static void glDrawArrays(int a0,int a1,int a2) { android.opengl.GLES32.glDrawArrays(a0,a1,a2); }
    public static void glDrawElements(int a0,int a1,int a2,int a3) { android.opengl.GLES32.glDrawElements(a0,a1,a2,a3); }
    public static void glDrawElements(int a0,int a1,int a2,java.nio.Buffer a3) { android.opengl.GLES32.glDrawElements(a0,a1,a2,a3); }
    public static void glEnable(int a0) { android.opengl.GLES32.glEnable(a0); }
    public static void glEnableVertexAttribArray(int a0) { android.opengl.GLES32.glEnableVertexAttribArray(a0); }
    public static void glFinish() { android.opengl.GLES32.glFinish(); }
    public static void glFlush() { android.opengl.GLES32.glFlush(); }
    public static void glFramebufferRenderbuffer(int a0,int a1,int a2,int a3) { android.opengl.GLES32.glFramebufferRenderbuffer(a0,a1,a2,a3); }
    public static void glFramebufferTexture2D(int a0,int a1,int a2,int a3,int a4) { android.opengl.GLES32.glFramebufferTexture2D(a0,a1,a2,a3,a4); }
    public static void glGenBuffers(int a0,int[] a1,int a2) { android.opengl.GLES32.glGenBuffers(a0,a1,a2); }
    public static void glGenBuffers(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glGenBuffers(a0,a1); }
    public static void glGenFramebuffers(int a0,int[] a1,int a2) { android.opengl.GLES32.glGenFramebuffers(a0,a1,a2); }
    public static void glGenFramebuffers(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glGenFramebuffers(a0,a1); }
    public static void glGenRenderbuffers(int a0,int[] a1,int a2) { android.opengl.GLES32.glGenRenderbuffers(a0,a1,a2); }
    public static void glGenRenderbuffers(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glGenRenderbuffers(a0,a1); }
    public static void glGenTextures(int a0,int[] a1,int a2) { android.opengl.GLES32.glGenTextures(a0,a1,a2); }
    public static void glGenTextures(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glGenTextures(a0,a1); }
    public static void glGenerateMipmap(int a0) { android.opengl.GLES32.glGenerateMipmap(a0); }
    public static void glGetIntegerv(int a0,int[] a1,int a2) { android.opengl.GLES32.glGetIntegerv(a0,a1,a2); }
    public static void glGetIntegerv(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glGetIntegerv(a0,a1); }
    public static void glGetProgramiv(int a0,int a1,int[] a2,int a3) { android.opengl.GLES32.glGetProgramiv(a0,a1,a2,a3); }
    public static void glGetProgramiv(int a0,int a1,java.nio.IntBuffer a2) { android.opengl.GLES32.glGetProgramiv(a0,a1,a2); }
    public static void glLinkProgram(int a0) { android.opengl.GLES32.glLinkProgram(a0); }
    public static void glReadPixels(int a0,int a1,int a2,int a3,int a4,int a5,java.nio.Buffer a6) { android.opengl.GLES32.glReadPixels(a0,a1,a2,a3,a4,a5,a6); }
    public static void glShaderSource(int a0,java.lang.String a1) { android.opengl.GLES32.glShaderSource(a0,a1); }
    public static void glTexImage2D(int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,java.nio.Buffer a8) { android.opengl.GLES32.glTexImage2D(a0,a1,a2,a3,a4,a5,a6,a7,a8); }
    public static void glTexParameterf(int a0,int a1,float a2) { android.opengl.GLES32.glTexParameterf(a0,a1,a2); }
    public static void glTexParameterfv(int a0,int a1,float[] a2,int a3) { android.opengl.GLES32.glTexParameterfv(a0,a1,a2,a3); }
    public static void glTexParameterfv(int a0,int a1,java.nio.FloatBuffer a2) { android.opengl.GLES32.glTexParameterfv(a0,a1,a2); }
    public static void glTexParameteri(int a0,int a1,int a2) { android.opengl.GLES32.glTexParameteri(a0,a1,a2); }
    public static void glTexSubImage2D(int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,java.nio.Buffer a8) { android.opengl.GLES32.glTexSubImage2D(a0,a1,a2,a3,a4,a5,a6,a7,a8); }
    public static void glUniform1f(int a0,float a1) { android.opengl.GLES32.glUniform1f(a0,a1); }
    public static void glUniform1i(int a0,int a1) { android.opengl.GLES32.glUniform1i(a0,a1); }
    public static void glUniform2f(int a0,float a1,float a2) { android.opengl.GLES32.glUniform2f(a0,a1,a2); }
    public static void glUniform2fv(int a0,int a1,float[] a2,int a3) { android.opengl.GLES32.glUniform2fv(a0,a1,a2,a3); }
    public static void glUniform2fv(int a0,int a1,java.nio.FloatBuffer a2) { android.opengl.GLES32.glUniform2fv(a0,a1,a2); }
    public static void glUniform2i(int a0,int a1,int a2) { android.opengl.GLES32.glUniform2i(a0,a1,a2); }
    public static void glUniform2iv(int a0,int a1,int[] a2,int a3) { android.opengl.GLES32.glUniform2iv(a0,a1,a2,a3); }
    public static void glUniform2iv(int a0,int a1,java.nio.IntBuffer a2) { android.opengl.GLES32.glUniform2iv(a0,a1,a2); }
    public static void glUniform3f(int a0,float a1,float a2,float a3) { android.opengl.GLES32.glUniform3f(a0,a1,a2,a3); }
    public static void glUniform3fv(int a0,int a1,float[] a2,int a3) { android.opengl.GLES32.glUniform3fv(a0,a1,a2,a3); }
    public static void glUniform3fv(int a0,int a1,java.nio.FloatBuffer a2) { android.opengl.GLES32.glUniform3fv(a0,a1,a2); }
    public static void glUniform3i(int a0,int a1,int a2,int a3) { android.opengl.GLES32.glUniform3i(a0,a1,a2,a3); }
    public static void glUniform3iv(int a0,int a1,int[] a2,int a3) { android.opengl.GLES32.glUniform3iv(a0,a1,a2,a3); }
    public static void glUniform3iv(int a0,int a1,java.nio.IntBuffer a2) { android.opengl.GLES32.glUniform3iv(a0,a1,a2); }
    public static void glUniform4f(int a0,float a1,float a2,float a3,float a4) { android.opengl.GLES32.glUniform4f(a0,a1,a2,a3,a4); }
    public static void glUniform4fv(int a0,int a1,float[] a2,int a3) { android.opengl.GLES32.glUniform4fv(a0,a1,a2,a3); }
    public static void glUniform4fv(int a0,int a1,java.nio.FloatBuffer a2) { android.opengl.GLES32.glUniform4fv(a0,a1,a2); }
    public static void glUniform4i(int a0,int a1,int a2,int a3,int a4) { android.opengl.GLES32.glUniform4i(a0,a1,a2,a3,a4); }
    public static void glUniform4iv(int a0,int a1,int[] a2,int a3) { android.opengl.GLES32.glUniform4iv(a0,a1,a2,a3); }
    public static void glUniform4iv(int a0,int a1,java.nio.IntBuffer a2) { android.opengl.GLES32.glUniform4iv(a0,a1,a2); }
    public static void glUniformMatrix4fv(int a0,int a1,boolean a2,float[] a3,int a4) { android.opengl.GLES32.glUniformMatrix4fv(a0,a1,a2,a3,a4); }
    public static void glUniformMatrix4fv(int a0,int a1,boolean a2,java.nio.FloatBuffer a3) { android.opengl.GLES32.glUniformMatrix4fv(a0,a1,a2,a3); }
    public static void glUseProgram(int a0) { android.opengl.GLES32.glUseProgram(a0); }
    public static void glValidateProgram(int a0) { android.opengl.GLES32.glValidateProgram(a0); }
    public static void glVertexAttribPointer(int a0,int a1,int a2,boolean a3,int a4,int a5) { android.opengl.GLES32.glVertexAttribPointer(a0,a1,a2,a3,a4,a5); }
    public static void glViewport(int a0,int a1,int a2,int a3) { android.opengl.GLES32.glViewport(a0,a1,a2,a3); }
    public static void glBindBufferBase(int a0,int a1,int a2) { android.opengl.GLES32.glBindBufferBase(a0,a1,a2); }
    public static void glBindVertexArray(int a0) { android.opengl.GLES32.glBindVertexArray(a0); }
    public static void glBlitFramebuffer(int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,int a8,int a9) { android.opengl.GLES32.glBlitFramebuffer(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9); }
    public static void glCopyBufferSubData(int a0,int a1,int a2,int a3,int a4) { android.opengl.GLES32.glCopyBufferSubData(a0,a1,a2,a3,a4); }
    public static void glDeleteQueries(int a0,int[] a1,int a2) { android.opengl.GLES32.glDeleteQueries(a0,a1,a2); }
    public static void glDeleteQueries(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glDeleteQueries(a0,a1); }
    public static void glDeleteSync(long a0) { android.opengl.GLES32.glDeleteSync(a0); }
    public static void glDeleteVertexArrays(int a0,int[] a1,int a2) { android.opengl.GLES32.glDeleteVertexArrays(a0,a1,a2); }
    public static void glDeleteVertexArrays(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glDeleteVertexArrays(a0,a1); }
    public static void glFlushMappedBufferRange(int a0,int a1,int a2) { android.opengl.GLES32.glFlushMappedBufferRange(a0,a1,a2); }
    public static void glFramebufferTextureLayer(int a0,int a1,int a2,int a3,int a4) { android.opengl.GLES32.glFramebufferTextureLayer(a0,a1,a2,a3,a4); }
    public static void glGenQueries(int a0,int[] a1,int a2) { android.opengl.GLES32.glGenQueries(a0,a1,a2); }
    public static void glGenQueries(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glGenQueries(a0,a1); }
    public static void glGenVertexArrays(int a0,int[] a1,int a2) { android.opengl.GLES32.glGenVertexArrays(a0,a1,a2); }
    public static void glGenVertexArrays(int a0,java.nio.IntBuffer a1) { android.opengl.GLES32.glGenVertexArrays(a0,a1); }
    public static void glGetProgramBinary(int a0,int a1,int[] a2,int a3,int[] a4,int a5,java.nio.Buffer a6) { android.opengl.GLES32.glGetProgramBinary(a0,a1,a2,a3,a4,a5,a6); }
    public static void glGetProgramBinary(int a0,int a1,java.nio.IntBuffer a2,java.nio.IntBuffer a3,java.nio.Buffer a4) { android.opengl.GLES32.glGetProgramBinary(a0,a1,a2,a3,a4); }
    public static void glReadBuffer(int a0) { android.opengl.GLES32.glReadBuffer(a0); }
    public static void glReadPixels(int a0,int a1,int a2,int a3,int a4,int a5,int a6) { android.opengl.GLES32.glReadPixels(a0,a1,a2,a3,a4,a5,a6); }
    public static void glRenderbufferStorageMultisample(int a0,int a1,int a2,int a3,int a4) { android.opengl.GLES32.glRenderbufferStorageMultisample(a0,a1,a2,a3,a4); }
    public static void glTexImage3D(int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,int a8,int a9) { android.opengl.GLES32.glTexImage3D(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9); }
    public static void glTexImage3D(int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,int a8,java.nio.Buffer a9) { android.opengl.GLES32.glTexImage3D(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9); }
    public static void glTexStorage3D(int a0,int a1,int a2,int a3,int a4,int a5) { android.opengl.GLES32.glTexStorage3D(a0,a1,a2,a3,a4,a5); }
    public static void glTexSubImage3D(int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,int a8,int a9,int a10) { android.opengl.GLES32.glTexSubImage3D(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10); }
    public static void glTexSubImage3D(int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,int a8,int a9,java.nio.Buffer a10) { android.opengl.GLES32.glTexSubImage3D(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10); }
    public static void glUniformBlockBinding(int a0,int a1,int a2) { android.opengl.GLES32.glUniformBlockBinding(a0,a1,a2); }
    public static void glVertexAttribDivisor(int a0,int a1) { android.opengl.GLES32.glVertexAttribDivisor(a0,a1); }
    public static void glVertexAttribIPointer(int a0,int a1,int a2,int a3,int a4) { android.opengl.GLES32.glVertexAttribIPointer(a0,a1,a2,a3,a4); }
    public static void glBindImageTexture(int a0,int a1,int a2,boolean a3,int a4,int a5,int a6) { android.opengl.GLES32.glBindImageTexture(a0,a1,a2,a3,a4,a5,a6); }
    public static void glDrawArraysIndirect(int a0,long a1) { android.opengl.GLES32.glDrawArraysIndirect(a0,a1); }
    public static void glDrawElementsIndirect(int a0,int a1,long a2) { android.opengl.GLES32.glDrawElementsIndirect(a0,a1,a2); }
    public static void glDebugMessageControl(int a0,int a1,int a2,int a3,int[] a4,int a5,boolean a6) { android.opengl.GLES32.glDebugMessageControl(a0,a1,a2,a3,a4,a5,a6); }
    public static void glDebugMessageControl(int a0,int a1,int a2,int a3,java.nio.IntBuffer a4,boolean a5) { android.opengl.GLES32.glDebugMessageControl(a0,a1,a2,a3,a4,a5); }
    public static void glFramebufferTexture(int a0,int a1,int a2,int a3) { android.opengl.GLES32.glFramebufferTexture(a0,a1,a2,a3); }
    public static void glObjectLabel(int a0,int a1,int a2,java.lang.String a3) { android.opengl.GLES32.glObjectLabel(a0,a1,a2,a3); }
    public static void glPopDebugGroup() { android.opengl.GLES32.glPopDebugGroup(); }
    public static void glPushDebugGroup(int a0,int a1,int a2,java.lang.String a3) { android.opengl.GLES32.glPushDebugGroup(a0,a1,a2,a3); }
    public static void glTexBuffer(int a0,int a1,int a2) { android.opengl.GLES32.glTexBuffer(a0,a1,a2); }
    public static void glVertexAttribPointer(int a0,int a1,int a2,boolean a3,int a4,java.nio.Buffer a5) { android.opengl.GLES32.glVertexAttribPointer(a0,a1,a2,a3,a4,a5); }
    public static void glVertexAttribIPointer(int a0,int a1,int a2,int a3,java.nio.Buffer a4) { android.opengl.GLES32.glVertexAttribIPointer(a0,a1,a2,a3,a4); }
}
